### PR TITLE
Docs remote debugging + custom backend + WildFly

### PR DESCRIPTION
**Pull request by ge0ffrey**
It took me some time to figure out how to set up a custom backend and how to remote debug it (there are a bunch of pitfalls), so I thought I 'd save others from those pitfalls by documenting it.

### CODE REVIEW

**Comment by tbroyer** [comment]
As explained in https://github.com/tbroyer/gwt-maven-plugin/issues/91#issuecomment-323756557, I don't want to document things that we don't actually want people to use.

**Comment by ge0ffrey** [comment]
@tbroyer You don't want people to do remote debugging?

**Comment by tbroyer** [comment]
You don't need to remote-debug "the server" if you don't have a server ;-)

The same configuration can be used to debug generators and linkers (and GWT itself, either the compiler or devmode/codeserver), but then codeserver.html might not be the best place for it (I'd also argue that you'd probably rather run `mvn -X` to get the classpath and arguments and then run that command right from your IDE –or the command-line– to debug the process, taking Maven out of the equation).

**Comment by ge0ffrey** [comment]
@tbroyer Christopher is working on getting us on "mvn gwt:codeserver" instead of "mvn gwt:devmode", with WildFly. Once that works, I still think that this plugin should document how to set up a custom server (such as WildFly) with GWT SDM and how to do remote debugging.

Would that documentation be welcome if we submit a PR for it? What would be the ideal file to document that in?

**Comment by tbroyer** [comment]
Hmm, I'd suggest that you do a first draft as a comment to this PR, so we can talk about it and see how best to handle it. wdyt?

**Comment by ge0ffrey** [comment]
FWIW, we've switched to "gwt:codeserver", here's how it works for us with a remote server, wildfly in our case: https://github.com/kiegroup/optashift-employee-rostering

**Pull request closed without merging**
